spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health
    hikari:
      maximum-pool-size: 4
    username: ksd
    password: "0000"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update