spring:
  application:
    name: health
  devtools:
    livereload:
      enabled: true
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: v-sch-
  web:
    resources:
      static-locations: file:src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:postgresql://localhost:5432/health
    hikari:
      maximum-pool-size: 4
    username: ksd
    password: 0000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update