spring:
  application:
    name: health
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: v-sch-
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800