spring:
  application:
    name: health
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: v-sch-
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800