spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/health-dev
    hikari:
      maximum-pool-size: 4
    username: ksd
    password: "0000"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update